### ISSUE TITLE
nil value in lua script

### ISSUE THREAD

**Issue by sgsokol** [quarto-journals/elsevier#10]
Hi,

When I try to render template.qmd from rstudio 2022.07.2 Build 576 I get following error:
```
Error running filter _extensions/elsevier/elsevier.lua:
_extensions/elsevier/elsevier.lua:60: attempt to call a nil value (field 'cite_method')
stack traceback:
```
Have I missed something, or currently it is in broken state?

**Comment by dragonstyle** [comment]
Can you please try updating your version of Quarto to the pre-release version (available at https://www.quarto.org)? We made some internal syntax changes that require a newer version (and starting with Quarto 1.2, we will provide a better error message that actually addresses the issue and advises you how to resolve instead of this unhelpful message!).

Sorry for the problem.

**Comment by sgsokol** [comment]
Thanks for the reply.
It is written in https://quarto.org/docs/tools/rstudio.html "If you are using Quarto within RStudio it is **strongly** recommended that you use this version" so being a novice in quarto, I'll stay with the version of Rstudio waiting for its update of quarto.
Thanks again.

**Comment by sgsokol** [comment]
Finally, I have taken a risk to install quarto-1.2.269-linux-amd64.deb, and it worked like a charm. Thanks.
