### ISSUE TITLE
Is it possible to add `subtitle`?

### ISSUE THREAD

**Issue by mingsu** [quarto-journals/elsevier#8]
Currently, subtitle in the `YAML` is ignored, can I suggest to add this parameter?

**Comment by dragonstyle** [comment]
I'm far from an expert on the Elsevier format, but in reading their documentation, I don't see any support for subtitles (which is why I omitted it). Do you, by chance, have more experience with Elsevier / could you point me at the correct handling of subtitles for Elsevier- I would be happy to add support and it should be easy once I know what the right thing to do is...

**Comment by mingsu** [comment]
After reading the document of `elsarticle.cls`, I have also noticed that this new version doesn't support `subtitle`.

It seems they use a more complicated package for subtitle and others, `cas-sc.cls` and `cas-dc.cls`, as shown below.

> For more complex articles two additional class files and templates are available, single-column (cas-sc.cls) and double-column (cas-dc.cls). These can be downloaded from [CTAN](https://www.ctan.org/pkg/els-cas-templates/) ([els-cas-template.zip](https://mirrors.ctan.org/macros/latex/contrib/els-cas-templates.zip)). These class files are documented [here](https://support.stmdocs.in/wiki/index.php?title=Elsarticle.cls).

In addition, the standard `article.cls` doesn't support `subtitle` command. By trying several workarounds, I think maybe just simply add `subtitle` inside of `title`.


```
> cat elsevier/partials/before-body.tex
...
\title{$title$ $if(subtitle)$ \\\large{$subtitle$} $endif$ }
...

```
